### ISSUE TITLE
Outdated information on creation of CI/CD

### ISSUE THREAD

**Issue by frederikja163** [opentap/opentap#1268]
https://doc.opentap.io/Developer%20Guide/Continuous%20Integration/

The documentation for creating CI/CD scripts to upload to the repo is outdated, specifically for the last two steps of the upload process.

It should instead be something similar to: 
```yml

        # Setup OpenTAP with the PackagePublish package in order to publish the newly created package
        - name: Setup OpenTAP
          uses: opentap/setup-opentap@v1.0
          with:
            version: 9.20.0
            packages: "Repository Client:beta"
        # Publish the package. This requires the package management key to be configured in the 'PUBLIC_REPO_PASS' environment variable.
        - name: Publish Packages
          working-directory: ./
          run: tap repo upload --repository http://packages.opentap.io --token ${{ secrets.PUBLIC_REPO_PASS }} Parquet*.TapPackage
```
