### ISSUE TITLE
opentap/setup-opentap should add additional repositories to the repository list

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1386]
e.g:
```yaml
      - name: Setup OpenTAP
        uses: opentap/setup-opentap@main
        with:
          version: 9.23.0
          packages: 'Repository Client:1.0.3-beta.1+7e104fcb'
          additional-repository: 'https://test-automation.pw.keysight.com/api/packages'
          additional-repository-token: '${{ SOME_REPO_TOKEN }}'
```

In this case, I'd expect the additional-repository value to be added to the package repository list, but actually it is only used to resolve the package.
